services:
    drivenops_db:
        image: postgres
        container_name: drivenops_db
        restart: always
        ports:
            - 2345:5432
        env_file:
            - back-end/.env.test

    drivenops_node:
        container_name: drivenops_node
        build: ./back-end
        ports:
            - 5000:5000
        depends_on:
            - drivenops_db
        env_file:
            - back-end/.env.test